Parte 1: Creación y manipulación de arrays
Creamos un array de 10 elementos enteros aleatorios entre 1 y 100

In [3]:
import numpy as np

array = np.random.randint(1, 101, size=10)
print("Arreglo generado:", array)

Arreglo generado: [32 43 82 53  6 17 18 14  6 11]


Reshape: Convertimos el arreglo en una matriz de 2x5

In [4]:
matriz_2x5 = array.reshape(2, 5)
print("\nMatriz 2x5:")
print(matriz_2x5)


Matriz 2x5:
[[32 43 82 53  6]
 [17 18 14  6 11]]


Indexación y slicing: Extraemos la primera fila y la última columna

In [5]:
primera_fila = matriz_2x5[0, :]
print("\nPrimera fila:", primera_fila)

ultima_columna = matriz_2x5[:, -1]
print("Última columna:", ultima_columna)


Primera fila: [32 43 82 53  6]
Última columna: [ 6 11]


Modificación: Cambiamos los valores de la segunda fila a ceros

In [6]:
matriz_2x5[1, :] = 0
print("\nMatriz con la segunda fila modificada:")
print(matriz_2x5)


Matriz con la segunda fila modificada:
[[32 43 82 53  6]
 [ 0  0  0  0  0]]


Parte 2: Operaciones básicas con NumPy
Operaciones aritméticas: Suma y multiplicación de arreglos

In [7]:
array1 = np.random.randint(1, 51, size=5)
array2 = np.random.randint(1, 51, size=5)

print("\nArray 1:", array1)
print("Array 2:", array2)

suma_arrays = array1 + array2
print("\nSuma de los arreglos:", suma_arrays)

multiplicacion_arrays = array1 * array2
print("Multiplicación de los arreglos:", multiplicacion_arrays)


Array 1: [20 31  8  9 13]
Array 2: [ 1 18 30 38 50]

Suma de los arreglos: [21 49 38 47 63]
Multiplicación de los arreglos: [ 20 558 240 342 650]


Cálculamos el promedio y la desviación estándar

In [8]:
promedio_suma = np.mean(suma_arrays)
desviacion_suma = np.std(suma_arrays)

promedio_multiplicacion = np.mean(multiplicacion_arrays)
desviacion_multiplicacion = np.std(multiplicacion_arrays)

print(f"\nPromedio de la suma: {promedio_suma}, Desviación estándar: {desviacion_suma}")
print(f"Promedio de la multiplicación: {promedio_multiplicacion}, Desviación estándar: {desviacion_multiplicacion}")


Promedio de la suma: 43.6, Desviación estándar: 13.850631754544628
Promedio de la multiplicación: 362.0, Desviación estándar: 225.21456436030064


Condiciones lógicas: Reemplazamos valores

In [9]:
array_random = np.random.rand(20)
print("\nArreglo original (entre 0 y 1):", array_random)

array_modificado = np.where(array_random < 0.5, 0, 1)
print("\nArreglo modificado con las condiciones lógicas:", array_modificado)


Arreglo original (entre 0 y 1): [0.90982922 0.36797711 0.70932592 0.34726123 0.38676578 0.0403294
 0.81448214 0.23780179 0.4508233  0.54066464 0.7769523  0.13465081
 0.72191851 0.16621982 0.28656999 0.42654103 0.69348477 0.08086174
 0.75440555 0.05460901]

Arreglo modificado con las condiciones lógicas: [1 0 1 0 0 0 1 0 0 1 1 0 1 0 0 0 1 0 1 0]


Producto escalar de dos arreglos de 3x3

In [10]:
array_3x3_1 = np.random.randint(1, 10, size=(3, 3))
array_3x3_2 = np.random.randint(1, 10, size=(3, 3))

print("\nArray 3x3 - 1:")
print(array_3x3_1)
print("\nArray 3x3 - 2:")
print(array_3x3_2)

producto_escalar = np.dot(array_3x3_1, array_3x3_2)
print("\nProducto escalar entre los arreglos 3x3:")
print(producto_escalar)


Array 3x3 - 1:
[[8 1 9]
 [2 2 9]
 [2 8 2]]

Array 3x3 - 2:
[[8 2 6]
 [2 5 2]
 [8 8 1]]

Producto escalar entre los arreglos 3x3:
[[138  93  59]
 [ 92  86  25]
 [ 48  60  30]]


Parte 3: Análisis de datos con NumPy
Matriz de datos de 5x4

In [11]:
matriz_datos = np.random.randint(1, 21, size=(5, 4))
print("\nMatriz de datos (5 filas y 4 columnas):")
print(matriz_datos)


Matriz de datos (5 filas y 4 columnas):
[[ 9 14 14 12]
 [14  7 11 15]
 [ 7 14 13  5]
 [ 1 18 10  6]
 [ 2  1  4  6]]


Estadísticas: Media, valor máximo y mínimo

In [12]:
media_columnas = np.mean(matriz_datos, axis=0)
print("\nMedia de cada columna:", media_columnas)

maximo_filas = np.max(matriz_datos, axis=1)
minimo_filas = np.min(matriz_datos, axis=1)

print("\nValor máximo de cada fila:", maximo_filas)
print("Valor mínimo de cada fila:", minimo_filas)


Media de cada columna: [ 6.6 10.8 10.4  8.8]

Valor máximo de cada fila: [14 15 14 18  6]
Valor mínimo de cada fila: [9 7 5 1 1]


Ordenamos las filas según la segunda columna

In [13]:
matriz_ordenada = matriz_datos[matriz_datos[:, 1].argsort()]
print("\nMatriz ordenada según la segunda columna (peso):")
print(matriz_ordenada)


Matriz ordenada según la segunda columna (peso):
[[ 2  1  4  6]
 [14  7 11 15]
 [ 7 14 13  5]
 [ 9 14 14 12]
 [ 1 18 10  6]]
